baseurl = "https://spokorsk.github.io/"
title = "Mon titre"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = false
disableKinds=["RSS"]
publishdir = "../blog.github.io/"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  description = '<!--[-->Un site réalisé par  <a href="https://html5up.net">HTML5 UP</a> <!--]--><br />
                <!--[-->Licence sous <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  #logo = "fa-diamond"
  logoimage = "/images/logo.png"
  copyright = '<!--[-->Thême utilisé et réalisé  par<!--]-->'
  Powerby = '<!--[-->Fait sur<!--]-->'

#[[params.social]]
#  medium = "twitter"
#  icon = "twitter"
#  link = "#"

#[[params.social]]
#  medium = "facebook"
#  icon = "facebook"
#  link = "#"

#[[params.social]]
#  medium = "instagram"
#  icon = "instagram"
#  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/spokorsk"

[languages]
[languages.fr]
languageName = "Français"
weight = 1

[languages.en]
languageName = "English"
weight = 2
title = "title"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
              <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
Powerby = '<!--[-->Power by<!--]-->'
copyright = '<!--[-->Used et Designed by<!--]-->'
